# ---- Build stage ----
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG REACT_APP_API_URL
ARG REACT_APP_WEBSOCKET_API_URL
ARG REACT_APP_DEBUG
ARG GENERATE_SOURCEMAP
ARG REACT_APP_ENABLE_POC_BUTTON
ARG REACT_APP_CURRENT_APP_VERSION
ARG PORT

ENV REACT_APP_API_URL=$REACT_APP_API_URL \
    REACT_APP_WEBSOCKET_API_URL=$REACT_APP_WEBSOCKET_API_URL \
    REACT_APP_DEBUG=$REACT_APP_DEBUG \
    GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP \
    REACT_APP_ENABLE_POC_BUTTON=$REACT_APP_ENABLE_POC_BUTTON \
    REACT_APP_CURRENT_APP_VERSION=$REACT_APP_CURRENT_APP_VERSION \
    PORT=$PORT

RUN npm run build

# ---- Serve stage ----
FROM node:18-slim
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/build ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
