#!/bin/bash

REACT_APP_API_URL=http://13.126.133.62:3001
REACT_APP_WEBSOCKET_API_URL=ws://13.126.133.62:3001/ws/job
REACT_APP_DEBUG=true
GENERATE_SOURCEMAP=false
PORT=3000
REACT_APP_ENABLE_POC_BUTTON=true
REACT_APP_CURRENT_APP_VERSION=2

IMAGE_NAME=$(grep 'IMAGE_NAME=' build.sh | cut -d '"' -f 2)
VERSION=$(grep 'VERSION=' build.sh | cut -d '"' -f 2)

docker run -e REACT_APP_VERSION=$VERSION -e REACT_APP_ENABLE_POC_BUTTON=$REACT_APP_ENABLE_POC_BUTTON  -e REACT_APP_API_URL=$REACT_APP_API_URL -e REACT_APP_WEBSOCKET_API_URL=$REACT_APP_WEBSOCKET_API_URL -e REACT_APP_DEBUG=$REACT_APP_DEBUG -e GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP -e REACT_APP_CURRENT_APP_VERSION=$REACT_APP_CURRENT_APP_VERSION -d -p $PORT:3000 $IMAGE_NAME:$VERSION