# Generated by Django 5.0.6 on 2024-11-15 09:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('dir', models.CharField(choices=[('GLOBAL', 'Global'), ('USER', 'User'), ('UNDIFINED', 'Undifined')], default='UNDIFINED', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='DELETED', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fileinfo', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_fileinfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FILEINFO',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('netlist_metadata', models.JSONField(null=True)),
                ('tech_metadata', models.JSONField(null=True)),
                ('action', models.IntegerField()),
                ('selectedLayouts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_projects', to=settings.AUTH_USER_MODEL)),
                ('stage_one_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_one_projects', to='ProjectManager.project')),
            ],
            options={
                'db_table': 'PROJECT',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted')], default='QUEUED', max_length=10)),
                ('log', models.TextField(blank=True, null=True)),
                ('command', models.TextField()),
                ('action', models.IntegerField()),
                ('cells', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('input', models.JSONField()),
                ('output', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ProjectManager.project')),
            ],
            options={
                'db_table': 'JOB',
            },
        ),
    ]
