# Generated by Django 5.1.3 on 2024-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
