# Generated by Django 5.1.3 on 2024-12-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_projecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='type',
            field=models.IntegerField(unique=True),
        ),
    ]
