# Generated by Django 5.1.3 on 2024-12-11 09:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_alter_projecttype_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('support_variation', models.BooleanField(default=False)),
                ('non_support_variation', models.BooleanField(default=False)),
                ('support_ui_visible', models.BooleanField(default=False)),
                ('non_support_ui_visible', models.BooleanField(default=False)),
                ('parameter_support_variation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TechInfo',
            },
        ),
        migrations.CreateModel(
            name='TechDetailedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('diplay_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('options_display_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('options_description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('project_type', models.IntegerField()),
                ('parameter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TechDetailedInfo',
            },
        ),
    ]
