# Generated by Django 5.1.3 on 2024-12-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_techinfo_techdetailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdetailedinfo',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.techinfo'),
        ),
    ]
