# Generated by Django 5.1.3 on 2024-12-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_alter_techdetailedinfo_parameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdetailedinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techdetailedinfo',
            name='support_variation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techdetailedinfo',
            name='ui_visible',
            field=models.BooleanField(default=False),
        ),
    ]
