# Generated by Django 5.1.3 on 2024-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_techdetailedinfo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinfo',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
