# Generated by Django 5.1.3 on 2024-12-29 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_techinfo_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cells',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
