# Generated by Django 5.1.3 on 2025-01-02 06:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_alter_job_cells'),
    ]

    operations = [
        migrations.AddField(
            model_name='techinfo',
            name='header',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
