# Generated by Django 5.1.3 on 2025-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_techinfo_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.IntegerField(default='1'),
        ),
    ]
