# Generated by Django 5.1.3 on 2025-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0012_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage_one_project',
            field=models.IntegerField(null=True),
        ),
    ]
