# Generated by Django 5.1.3 on 2025-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0013_alter_project_stage_one_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdetailedinfo',
            name='negative_end_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techdetailedinfo',
            name='negative_start_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techdetailedinfo',
            name='stepper',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='techdetailedinfo',
            name='stepper_float',
            field=models.BooleanField(default=False),
        ),
    ]
