# Generated by Django 5.1.3 on 2025-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0014_techdetailedinfo_negative_end_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdetailedinfo',
            name='stepper',
            field=models.FloatField(default=1),
        ),
    ]
