# Generated by Django 5.1.3 on 2025-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0015_alter_techdetailedinfo_stepper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techdetailedinfo',
            name='stepper',
            field=models.FloatField(default=1, null=True),
        ),
    ]
