# Generated by Django 5.1.3 on 2025-04-28 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0017_techdetailedinfo_defaultendvalue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechFileCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField()),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('tech_data', models.JSONField(blank=True, null=True)),
                ('drc_count', models.IntegerField(default=0)),
                ('lvs_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted')], default='QUEUED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tech_files', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_files', to='ProjectManager.project')),
            ],
            options={
                'db_table': 'TechFileCatalog',
            },
        ),
    ]
