# Generated by Django 5.1.3 on 2025-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0018_techfilecatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfilecatalog',
            name='cell_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
