# Generated by Django 5.1.3 on 2025-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0019_alter_techfilecatalog_cell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techfilecatalog',
            name='status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('DELETED', 'Deleted')], max_length=10, null=True),
        ),
    ]
