# Generated by Django 5.1.3 on 2025-05-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0021_alter_techfilecatalog_drc_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='filesize',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
