# Generated by Django 5.1.3 on 2025-06-06 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0022_fileinfo_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='selectedLayouts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
    ]
