# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_stream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protobuf_stream.proto\x12\x06layout\x1a\x1cgoogle/protobuf/struct.proto\"\xe9\x01\n\x10LayoutGenRequest\x12\x14\n\x0cnetlist_data\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0c\n\x04\x63\x65ll\x18\x03 \x01(\t\x12\x11\n\ts3_prefix\x18\x04 \x01(\t\x12\x11\n\ttech_json\x18\x05 \x01(\t\x12\x34\n\x06params\x18\x06 \x03(\x0b\x32$.layout.LayoutGenRequest.ParamsEntry\x1a\x45\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"2\n\x0fSiVistaResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x92\x02\n\x18HyperexpressivityRequest\x12\x17\n\x0fgds_folder_path\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0c\n\x04\x63\x65ll\x18\x03 \x01(\t\x12\x11\n\ts3_prefix\x18\x04 \x01(\t\x12\x14\n\x0cnetlist_data\x18\x05 \x01(\t\x12\x11\n\ttech_json\x18\x06 \x01(\t\x12<\n\x06params\x18\x07 \x03(\x0b\x32,.layout.HyperexpressivityRequest.ParamsEntry\x1a\x45\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"\x07\n\x05\x45mpty\"$\n\x0f\x46ilePathRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t2\x96\x02\n\rSiVistaLayout\x12@\n\tLayoutGen\x12\x18.layout.LayoutGenRequest\x1a\x17.layout.SiVistaResponse0\x01\x12P\n\x11Hyperexpressivity\x12 .layout.HyperexpressivityRequest\x1a\x17.layout.SiVistaResponse0\x01\x12\x34\n\nGetVersion\x12\r.layout.Empty\x1a\x17.layout.SiVistaResponse\x12;\n\x07GetFile\x12\x17.layout.FilePathRequest\x1a\x17.layout.SiVistaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LAYOUTGENREQUEST_PARAMSENTRY']._options = None
  _globals['_LAYOUTGENREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_HYPEREXPRESSIVITYREQUEST_PARAMSENTRY']._options = None
  _globals['_HYPEREXPRESSIVITYREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_LAYOUTGENREQUEST']._serialized_start=64
  _globals['_LAYOUTGENREQUEST']._serialized_end=297
  _globals['_LAYOUTGENREQUEST_PARAMSENTRY']._serialized_start=228
  _globals['_LAYOUTGENREQUEST_PARAMSENTRY']._serialized_end=297
  _globals['_SIVISTARESPONSE']._serialized_start=299
  _globals['_SIVISTARESPONSE']._serialized_end=349
  _globals['_HYPEREXPRESSIVITYREQUEST']._serialized_start=352
  _globals['_HYPEREXPRESSIVITYREQUEST']._serialized_end=626
  _globals['_HYPEREXPRESSIVITYREQUEST_PARAMSENTRY']._serialized_start=228
  _globals['_HYPEREXPRESSIVITYREQUEST_PARAMSENTRY']._serialized_end=297
  _globals['_EMPTY']._serialized_start=628
  _globals['_EMPTY']._serialized_end=635
  _globals['_FILEPATHREQUEST']._serialized_start=637
  _globals['_FILEPATHREQUEST']._serialized_end=673
  _globals['_SIVISTALAYOUT']._serialized_start=676
  _globals['_SIVISTALAYOUT']._serialized_end=954
# @@protoc_insertion_point(module_scope)
