apiVersion: v1
kind: ConfigMap
metadata:
  name: sivista-frontend-config
  namespace: default
data:
  REACT_APP_API_URL: "http://13.126.133.62:6601"
  REACT_APP_WEBSOCKET_API_URL: "ws://13.126.133.62:6601/ws/job"
  REACT_APP_DEBUG: "true"
  GENERATE_SOURCEMAP: "false"
  REACT_APP_ENABLE_POC_BUTTON: "true"
  REACT_APP_CURRENT_APP_VERSION: "2"
  PORT: "3000"