apiVersion: apps/v1
kind: Deployment
metadata:
  name: sivista-be-deployment
  labels:
    app: sivista-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivista-be
  template:
    metadata:
      labels:
        app: sivista-be
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: sivista-backend
          image: ghcr.io/devang-k/k8s/sivista_backend_sprint4:1.0.0.370
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: dev-config
            - secretRef:
                name: dev-secrets
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
