apiVersion: apps/v1
kind: Deployment
metadata:
  name: sivista-be-deployment
  labels:
    app: sivista-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivista-be
  template:
    metadata:
      labels:
        app: sivista-be
    spec:
      containers:
      - name: sivista-backend
        image: siclarity/sivista_backend_sprint4:${VERSION}
        image: ghcr.io/devang-k/k8s/sivista_frontend_sprint4:1.0.0.415
        ports:
        - containerPort: 8000