apiVersion: apps/v1
kind: Deployment
metadata:
  name: sivista-be-deployment
  labels:
    app: sivista-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivista-be
  template:
    metadata:
      labels:
        app: sivista-be
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: sivista-backend
          image: "ghcr.io/devang-k/k8s/sivista_backend_sprint4:${VERSION}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: VERSION
              value: "${VERSION}"
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
