apiVersion: apps/v1
kind: Deployment
metadata:
  name: sivista-frontend
  namespace: default
  labels:
    app: sivista-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sivista-frontend
  template:
    metadata:
      labels:
        app: sivista-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: sivista-frontend
          image: ghcr.io/devang-k/k8s/sivista_frontend_sprint4:1.0.0.415
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://13.126.133.62:6601"
            - name: REACT_APP_WEBSOCKET_API_URL
              value: "ws://13.126.133.62:6601/ws/job"
            - name: REACT_APP_DEBUG
              value: "true"
            - name: GENERATE_SOURCEMAP
              value: "false"
            - name: REACT_APP_ENABLE_POC_BUTTON
              value: "true"
            - name: REACT_APP_CURRENT_APP_VERSION
              value: "2"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"