apiVersion: v1
kind: Service
metadata:
  name: sivista-frontend-service
  namespace: default
spec:
  selector:
    app: sivista-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort