apiVersion: v1
kind: Service
metadata:
  name: sivista-be-service
spec:
  selector:
    app: sivista-be
  ports:
    - protocol: TCP
      port: 6601
      targetPort: 8000
      nodePort: 30001
  type: NodePort