ADMIN_USERNAME='ADMIN'
NAME='ADMIN'
ADMIN_EMAIL='admin@example.com'
ADMIN_PASSWORD='S!Clar!ty@12345'

project_types = [
            ('NORMAL', 0, True),
            ('200+ Transistors', 2, False),
            ('RL', 1, False)
        ]
#id, name, support_variation, non_support_variation, support_ui_visible, non_support_ui_visible, parameter_support_variation, display_name, header 
tech_info_data = [
            (1, 'layer_map', False, False, True, True, False, 'Layer Map', '{Layer,"Layer Number","Data Type"}'),
            (2, 'tech_constaints', True, False, True, True, True, 'Technology & Design Constraints', None),
            (3, 'other', True, False, True, True, True, 'Design Rules', None),
            (4, 'layer_width', True, False, True, True, True, 'Width and Pitch Rules', None),
            (5, 'min_spacing', True, False, True, True, True, 'Spacing Rules', None),
            (6, 'routing_order', False, False, False, False, True, None, None),
            (7, 'hinder', False, False, False, False, False, None, None),
            (8, 'configs', False, False, False, False, False, None, None),
            (9, 'weights_horizontal', False, False, False, False, False, None, None),
            (10, 'weights_vertical', False, False, False, False, False, None, None),
            (11, 'via_weights', False, False, False, False, False, None, None),
            (12, 'routing_layers', False, False, False, False, False, None, None),
            (13, 'via_size', False, False, False, False, False, None, None),
            (14, 'minimum_enclosure', False, False, False, False, False, None, None),
            (15, 'layer_properties', False, False, False, False, False, None, None),
            (16, 'permutation', False, False, True, False, False, 'Permutation', None),
            (17, 'display_names', False, False, False, False, False, 'Display Names', None),
        ]

tech_detailed_info_data = [
			(1,'{ndiffcon}','{ndiffcon}',None,'ndiffusion interconnect',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(2,'{pdiffcon}','{pdiffcon}',None,'pdiffusion interconnect',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(3,'{ndiff}','{ndiff}',None,'n-type nanosheet',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(4,'{pdiff}','{pdiff}',None,'p-type nanosheet',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(5,'{nwell}','{nwell}',None,'In FinFET only, N type well',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(6,'{npoly}','{npoly}',None,'gate(poly) for nmos',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(7,'{gate_isolation}','{"Gate isolation"}',None,'In CFET only, gate isolation for split gates',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(8,'{dummy_gate}','{"Dummy gate"}',None,'Ends the cell in X direction',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(9,'{ppoly}','{ppoly}',None,'gate(poly) for pmos',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(10,'{pviag}','{pviag}',None,'ppoly to Metal0',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(11,'{nviag}','{nviag}',None,'npoly to Metal0',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(12,'{ndiff_dvb}','{"ndiff dvb"}',None,'Deep via boundary connects ndiffusion to power rail',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(13,'{pdiff_dvb}','{"pdiff dvb"}',None,'Deep via boundary connects pdiffusion to power rail',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(14,'{metal0}','{M0}',None,'Metal0 (horizontal routing)',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(15,'{metal0_label}','{"M0 label"}',None,'Metal0 label (horizontal routing)',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(16,'{metal0_pin}','{"M0 pin"}',None,'Metal0 pin',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(17,'{metal0_pin_label}','{"M0 pin label"}',None,'Metal0 pin label',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(18,'{metal0_track_guide}','{"M0 track guide"}',None,'Horizontal Metal0 tracks',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(19,'{diff_interconnect}','{"Diff interconnect"}',None,'In CFET only, pdiffusion and ndiffusion interconnect via',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(20,'{pviat}','{pviat}',None,'pdiffusion to Metal0',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(21,'{nviat}','{nviat}',None,'ndiffusion to Metal0',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(22,'{back_metal0}','{BM0}',None,'Back side power rail',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(23,'{back_metal0_label}','{"BM0 label"}',None,'Back side power rail label',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(24,'{back_metal0_pin}','{"BM0 pin"}',None,'Back side power rail pin',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(25,'{back_metal0_pin_label}','{"BM0 pin label"}',None,'Back side power rail pin label',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(26,'{cell_boundary}','{"Cell boundary"}',None,'Cell boundary',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(27,'{bspdn_pmos_via}','{bspdn_pmos_via}',None,'In CFET only,pdiffusion to power rail',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(28,'{metal1}','{M1}',None,'Metal1 (vertical routing)',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(29,'{metal1_label}','{"M1 label"}',None,'Metal1 label (vertical routing)',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(30,'{metal1_track_guide}','{"M1 track guide"}',None,'Vertical Metal1 tracks',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(31,'{via0}','{via0}',None,'Metal0 and Metal1 interconnect via',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(32,'{metal1_pin}','{"M1 pin"}',None,'Metal1 pin',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(33,'{metal1_pin_label}','{"M1 pin label"}',None,'Metal1 pin label',None,None,None,0,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(34,'{flipped}','{Orientation}',None,'To flip the layout','{R0,Mx,My}','{"R0 ( No flip)","Mx ( Flip along X axis)","My ( Flip along Y axis)"}','{"Default - No flip","Layout flipped along X axis","Layout flipped along Y axis"}',0,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(35,'{backside_power_rail}','{"Power Distribution"}',None,'Option for Topside and Backside Power','{Backside power,Frontside power}','{Backside power,Frontside power}','{"Routing tracks present over the power rail","Routing tracks not present over the power rail"}',0,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(36,'{routing_capability}','{"Routing Capability"}',None,'Routing in Single Metal or with Two Metals','{"Single Metal Solution","Two Metal Solution"}','{"Single Metal Solution","Two Metal Solution"}','{"Routing done in single metal M0(horizontal)","Routing may utilize second metal(metal1, vertical) if first metal (metal0) resources are exhausted or if placement & routing track combination requires vertical routing"}',0,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(37,'{technology}','{Technology}',None,'Type of technology','{cfet,gaa,finfet}','{CFET,GAA,FinFET}','{"Select cfet technology","Select gaa technology","Select finFET technology"}',0,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(38,'{half_dr}','{"Half DR Compliance"}',None,'Switch for Half DR compliance','{True,False}','{True,False}','{"Generates half DR compliant layouts","Generates half DR non-compliant layouts"}',0,2,True,False,False,False,False,False,1,None,None,None,None,None,None,None,None),
			(39,'{number_of_routing_tracks}','{"Number of routing tracks"}',None,'Number of routing tracks per cell',None,None,None,0,2,True,True,True,False,False,False,1,2,98,3,99,2,7,None,None),
			(40,'{height_req}','{"Height Requirement"}',None,'Controls height of mult-height cell',None,None,None,0,3,True,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(41,'{placer}','{Placer}',None,'Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon','{base0,base1}','{base0,base1}','{"Uses base0 placement algorithm","Uses base1 placement algorithm"}',0,3,True,True,False,False,False,False,1,None,None,None,None,None,None,None,None),
			(42,'{inner_space_width}','{"Poly to Diffcon spacing"}','nm','Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon',None,None,None,0,5,True,True,True,False,False,True,0.5,3,7,4,8,3,8,None,None),
			(43,'{"np_spacing"}', '{"N/P Diffusion spacing"}', 'nm', 'In GAA and FinFET only, the distance between pdiff and ndiff', None, None, None, 0,5, True, True, True,False,False,True,0.5,30,49,31,50,30,50,None,None),
			(44,'{"pg_signal_spacing"}', '{"PG rails to Signal spacing"}', 'nm', 'For Frontside Power, distance between power/ground and signals for Metal0', None, None, None, 0,5, True, True, True,False,False,True,0.5,5,14,6,15,5,15,None,None),	
	 		(45,'{nanosheet,diff_interconnect}','{"Diffusion to Diff interconnect spacing"}','nm','In CFET only, Minimum spacing between Diffusion and Diff interconnect',None,None,None,0,5,True,True,True,False,False,True,0.5,10,24,11,25,10,25,None,None),
			(46,'{"via_extension"}','{"Via extension"}','nm','Used to change the all vias(except dvb, Diff Interconnect) size in both X and Y direction simultaneously',None,None,None,0,5,True,True,True,False,False,True,0.5,0,2,1,3,0,3,None,None),
	 		(47,'{"gate_extension"}','{"Gate extension"}','nm','Extension of poly layer from diffusion(nanosheet)',None,None,None,0,5,True,True,True,False,False,True,0.5,8,19,9,20,8,20,None,None),
	 		(48,'{"interconnect_extension"}','{"Diffcon extension"}','nm','Extension of Diffcon layer from diffusion(nanosheet)',None,None,None,0,5,True,True,True,False,False,True,0.5,0,9,10,10,9,10,None,None),
	 		(49,'{"vertical_gate_spacing"}','{"Gate Cut spacing"}','nm','In GAA & FinFET only, end to end spacing between ppoly and npoly',None,None,None,0,5,True,True,True,False,False,True,0.5,5,14,6,15,5,15,None,None),
	 		(50,'{"vertical_interconnect_spacing"}','{"Diffcon ETE spacing"}','nm','For GAA and FinFET only, end to end spacing between pdiffcon and ndiffcon',None,None,None,0,5,True,True,True,False,False,True,0.5,10,24,11,25,10,25,None,None),
	 		(51,'{nanosheet_width}','{"Diffusion width"}','nm','Width of Diffusion/Nanosheet',None,None,None,0,4,True,True,True,False,False,True,0.5,15,39,16,40,15,40,None,None),
	 		(52,'{power_rail_width}','{"Power rail width"}','nm','Width of back metal power rail',None,None,None,0,4,True,True,True,False,False,True,0.5,20,49,21,50,20,50,None,None),
	 		(53,'{m0_pitch}','{"Metal0 routing pitch"}','nm','Routing pitch for horizontal metal( Metal0)',None,None,None,0,4,True,True,True,False,False,True,0.5,20,29,21,30,20,30,None,None),
	 		(54,'{"vertical_metal_pitch"}','{"Metal1 routing pitch"}','nm','For Two metal solution, routing pitch for vertical metal (Metal1,None,None,None,None,None,None,None,None)',None,None,None,0,4,True,True,True,False,False,True,0.5,20,47,21,48,20,48,None,None),
	 		(55,'{pdiffcon}','{"P-diffcon width"}','nm','Changes cell width',None,None,None,0,4,True,True,True,False,False,True,0.5,8,19,9,20,8,20,None,None),
	 		(56,'{npoly}','{"N-poly width"}','nm','Transistor gate length of nFET is changed',None,None,None,0,4,True,True,True,False,False,True,0.5,3,19,4,20,3,20,None,None),
	 		(57,'{ppoly}','{"P-poly width"}','nm','Transistor gate length of pFET is changed',None,None,None,0,4,True,True,True,False,False,True,0.5,3,19,4,20,3,20,None,None),
	 		(58,'{metal0}','{"M0 width"}','nm','Width of Metal0 Wire (Y direction)',None,None,None,0,4,True,True,True,False,False,True,0.5,8,14,9,15,8,15,None,None),
	 		(59,'{ndiffcon}','{"N-diffcon width"}','nm','Changes cell width',None,None,None,0,4,True,True,True,False,False,True,0.5,8,19,9,20,8,20,None,None),
	 		(60,'{metal0_track_guide}','{"M0 track guide"}','nm','Width of Metal0 tracks (Y direction) for visualization for foundry users',None,None,None,0,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(61,'{metal1}','{"M1 width"}','nm','Width of Metal1 Wire (X direction)',None,None,None,0,4,True,True,True,False,False,True,0.5,8,27,9,28,8,28,None,None),
	 		(62,'{metal1_track_guide}','{"M1 track guide"}','nm','Width of Metal1 tracks (X direction) for visualization for foundry users',None,None,None,0,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(63,'{poly}','{"poly"}','nm','Length of poly (X direction)',None,None,None,0,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(64,'{diffcon}','{"diffcon"}','nm','Length of diffcon (X direction)',None,None,None,0,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(65,'{ndiffcon}','{ndiffcon}',None,'ndiffusion interconnect',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(66,'{pdiffcon}','{pdiffcon}',None,'pdiffusion interconnect',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(67,'{ndiff}','{ndiff}',None,'n-type nanosheet',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(68,'{pdiff}','{pdiff}',None,'p-type nanosheet',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(69,'{nwell}','{nwell}',None,'In FinFET only, N type well',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(70,'{npoly}','{npoly}',None,'gate(poly) for nmos',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(71,'{gate_isolation}','{"Gate isolation"}',None,'In CFET only, gate isolation for split gates',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(72,'{dummy_gate}','{"Dummy gate"}',None,'Ends the cell in X direction',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(73,'{ppoly}','{ppoly}',None,'gate(poly) for pmos',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(74,'{pviag}','{pviag}',None,'ppoly to Metal0',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(75,'{nviag}','{nviag}',None,'npoly to Metal0',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(76,'{ndiff_dvb}','{"ndiff dvb"}',None,'Deep via boundary connects ndiffusion to power rail',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(77,'{pdiff_dvb}','{"pdiff dvb"}',None,'Deep via boundary connects pdiffusion to power rail',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(78,'{metal0}','{M0}',None,'Metal0 (horizontal routing)',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(79,'{metal0_label}','{"M0 label"}',None,'Metal0 label (horizontal routing)',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(80,'{metal0_pin}','{"M0 pin"}',None,'Metal0 pin',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(81,'{metal0_pin_label}','{"M0 pin label"}',None,'Metal0 pin label',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(82,'{metal0_track_guide}','{"M0 track guide"}',None,'Horizontal Metal0 tracks',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(83,'{diff_interconnect}','{"Diff interconnect"}',None,'In CFET only, pdiffusion and ndiffusion interconnect via',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(84,'{pviat}','{pviat}',None,'pdiffusion to Metal0',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(85,'{nviat}','{nviat}',None,'ndiffusion to Metal0',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(86,'{back_metal0}','{BM0}',None,'Back side power rail',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(87,'{back_metal0_label}','{"BM0 label"}',None,'Back side power rail label',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(88,'{back_metal0_pin}','{"BM0 pin"}',None,'Back side power rail pin',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(89,'{back_metal0_pin_label}','{"BM0 pin label"}',None,'Back side power rail pin label',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(90,'{cell_boundary}','{"Cell boundary"}',None,'Cell boundary',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(91,'{bspdn_pmos_via}','{bspdn_pmos_via}',None,'In CFET only,pdiffusion to power rail',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(92,'{metal1}','{M1}',None,'Metal1 (vertical routing)',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(93,'{metal1_label}','{"M1 label"}',None,'Metal1 label (vertical routing)',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(94,'{metal1_track_guide}','{"M1 track guide"}',None,'Vertical Metal1 tracks',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(95,'{via0}','{via0}',None,'Metal0 and Metal1 interconnect via',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(96,'{metal1_pin}','{"M1 pin"}',None,'Metal1 pin',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(97,'{metal1_pin_label}','{"M1 pin label"}',None,'Metal1 pin label',None,None,None,1,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(98,'{flipped}','{Orientation}',None,'To flip the layout','{R0,Mx,My}','{"R0 ( No flip)","Mx ( Flip along X axis)","My ( Flip along Y axis)"}','{"Default - No flip","Layout flipped along X axis","Layout flipped along Y axis"}',1,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(99,'{backside_power_rail}','{"Power Distribution"}',None,'Option for Topside and Backside Power','{Backside power,Frontside power}','{Backside power,Frontside power}','{"Routing tracks present over the power rail","Routing tracks not present over the power rail"}',1,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(100,'{routing_capability}','{"Routing Capability"}',None,'Routing in Single Metal or with Two Metals','{"Single Metal Solution","Two Metal Solution"}','{"Single Metal Solution","Two Metal Solution"}','{"Routing done in single metal M0(horizontal)","Routing may utilize second metal(metal1, vertical) if first metal (metal0) resources are exhausted or if placement & routing track combination requires vertical routing"}',1,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(101,'{technology}','{Technology}',None,'Type of technology','{cfet,gaa,finfet}','{CFET,GAA,FinFET}','{"Select cfet technology","Select gaa technology","Select finFET technology"}',1,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(102,'{half_dr}','{"Half DR Compliance"}',None,'Switch for Half DR compliance','{True,False}','{True,False}','{"Generates half DR compliant layouts","Generates half DR non-compliant layouts"}',1,2,True,False,False,False,False,False,1,None,None,None,None,None,None,None,None),
			(103,'{number_of_routing_tracks}','{"Number of routing tracks"}',None,'Number of routing tracks per cell',None,None,None,1,2,True,True,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(104,'{height_req}','{"Height Requirement"}',None,'Controls height of mult-height cell',None,None,None,1,3,True,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(105,'{placer}','{Placer}',None,'Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon','{base0,base1}','{base0,base1}','{"Uses base0 placement algorithm","Uses base1 placement algorithm"}',1,3,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(106,'{inner_space_width}','{"Poly to Diffcon spacing"}','nm','Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(107,'{"np_spacing"}', '{"N/P Diffusion spacing"}', 'nm', 'In GAA and FinFET only, the distance between pdiff and ndiff', None, None, None, 1,5, True, True, True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(108,'{"pg_signal_spacing"}', '{"PG rails to Signal spacing"}', 'nm', 'For Frontside Power, distance between power/ground and signals for Metal0', None, None, None, 1,5, True, True, True,False,False,True,0.5,None,None,None,None,None,None,None,None),	
	 		(109,'{nanosheet,diff_interconnect}','{"Diffusion to Diff interconnect spacing"}','nm','In CFET only, Minimum spacing between Diffusion and Diff interconnect',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(110,'{"via_extension"}','{"Via extension"}','nm','Used to change the all vias(except dvb, Diff Interconnect) size in both X and Y direction simultaneously',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(111,'{"gate_extension"}','{"Gate extension"}','nm','Extension of poly layer from diffusion(nanosheet)',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(112,'{"interconnect_extension"}','{"Diffcon extension"}','nm','Extension of Diffcon layer from diffusion(nanosheet)',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(113,'{"vertical_gate_spacing"}','{"Gate Cut spacing"}','nm','In GAA & FinFET only, end to end spacing between ppoly and npoly',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(114,'{"vertical_interconnect_spacing"}','{"Diffcon ETE spacing"}','nm','For GAA and FinFET only, end to end spacing between pdiffcon and ndiffcon',None,None,None,1,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(115,'{nanosheet_width}','{"Diffusion width"}','nm','Width of Diffusion/Nanosheet',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(116,'{power_rail_width}','{"Power rail width"}','nm','Width of back metal power rail',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(117,'{m0_pitch}','{"Metal0 routing pitch"}','nm','Routing pitch for horizontal metal( Metal0)',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(118,'{"vertical_metal_pitch"}','{"Metal1 routing pitch"}','nm','For Two metal solution, routing pitch for vertical metal (Metal1,None,None,None,None,None,None,None,None)',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(119,'{pdiffcon}','{"P-diffcon width"}','nm','Changes cell width',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(120,'{npoly}','{"N-poly width"}','nm','Transistor gate length of nFET is changed',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(121,'{ppoly}','{"P-poly width"}','nm','Transistor gate length of pFET is changed',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(122,'{metal0}','{"M0 width"}','nm','Width of Metal0 Wire (Y direction)',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(123,'{ndiffcon}','{"N-diffcon width"}','nm','Changes cell width',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(124,'{metal0_track_guide}','{"M0 track guide"}','nm','Width of Metal0 tracks (Y direction) for visualization for foundry users',None,None,None,1,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(125,'{metal1}','{"M1 width"}','nm','Width of Metal1 Wire (X direction)',None,None,None,1,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(126,'{metal1_track_guide}','{"M1 track guide"}','nm','Width of Metal1 tracks (X direction) for visualization for foundry users',None,None,None,1,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(127,'{poly}','{"poly"}','nm','Length of poly (X direction)',None,None,None,1,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(128,'{diffcon}','{"diffcon"}','nm','Length of diffcon (X direction)',None,None,None,1,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(129,'{ndiffcon}','{ndiffcon}',None,'ndiffusion interconnect',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(130,'{pdiffcon}','{pdiffcon}',None,'pdiffusion interconnect',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(131,'{ndiff}','{ndiff}',None,'n-type nanosheet',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(132,'{pdiff}','{pdiff}',None,'p-type nanosheet',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(133,'{nwell}','{nwell}',None,'In FinFET only, N type well',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(134,'{npoly}','{npoly}',None,'gate(poly) for nmos',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(135,'{gate_isolation}','{"Gate isolation"}',None,'In CFET only, gate isolation for split gates',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(136,'{dummy_gate}','{"Dummy gate"}',None,'Ends the cell in X direction',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(137,'{ppoly}','{ppoly}',None,'gate(poly) for pmos',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(138,'{pviag}','{pviag}',None,'ppoly to Metal0',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(139,'{nviag}','{nviag}',None,'npoly to Metal0',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(140,'{ndiff_dvb}','{"ndiff dvb"}',None,'Deep via boundary connects ndiffusion to power rail',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(141,'{pdiff_dvb}','{"pdiff dvb"}',None,'Deep via boundary connects pdiffusion to power rail',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(142,'{metal0}','{M0}',None,'Metal0 (horizontal routing)',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(143,'{metal0_label}','{"M0 label"}',None,'Metal0 label (horizontal routing)',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(144,'{metal0_pin}','{"M0 pin"}',None,'Metal0 pin',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(145,'{metal0_pin_label}','{"M0 pin label"}',None,'Metal0 pin label',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(146,'{metal0_track_guide}','{"M0 track guide"}',None,'Horizontal Metal0 tracks',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(147,'{diff_interconnect}','{"Diff interconnect"}',None,'In CFET only, pdiffusion and ndiffusion interconnect via',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(148,'{pviat}','{pviat}',None,'pdiffusion to Metal0',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(149,'{nviat}','{nviat}',None,'ndiffusion to Metal0',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(150,'{back_metal0}','{BM0}',None,'Back side power rail',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(151,'{back_metal0_label}','{"BM0 label"}',None,'Back side power rail label',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(152,'{back_metal0_pin}','{"BM0 pin"}',None,'Back side power rail pin',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(153,'{back_metal0_pin_label}','{"BM0 pin label"}',None,'Back side power rail pin label',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(154,'{cell_boundary}','{"Cell boundary"}',None,'Cell boundary',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(155,'{bspdn_pmos_via}','{bspdn_pmos_via}',None,'In CFET only,pdiffusion to power rail',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(156,'{metal1}','{M1}',None,'Metal1 (vertical routing)',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(157,'{metal1_label}','{"M1 label"}',None,'Metal1 label (vertical routing)',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(158,'{metal1_track_guide}','{"M1 track guide"}',None,'Vertical Metal1 tracks',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(159,'{via0}','{via0}',None,'Metal0 and Metal1 interconnect via',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(160,'{metal1_pin}','{"M1 pin"}',None,'Metal1 pin',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(161,'{metal1_pin_label}','{"M1 pin label"}',None,'Metal1 pin label',None,None,None,2,1,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(162,'{flipped}','{Orientation}',None,'To flip the layout','{R0,Mx,My}','{"R0 ( No flip)","Mx ( Flip along X axis)","My ( Flip along Y axis)"}','{"Default - No flip","Layout flipped along X axis","Layout flipped along Y axis"}',2,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(163,'{backside_power_rail}','{"Power Distribution"}',None,'Option for Topside and Backside Power','{Backside power,Frontside power}','{Backside power,Frontside power}','{"Routing tracks present over the power rail","Routing tracks not present over the power rail"}',2,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(164,'{routing_capability}','{"Routing Capability"}',None,'Routing in Single Metal or with Two Metals','{"Single Metal Solution","Two Metal Solution"}','{"Single Metal Solution","Two Metal Solution"}','{"Routing done in single metal M0(horizontal)","Routing may utilize second metal(metal1, vertical) if first metal (metal0) resources are exhausted or if placement & routing track combination requires vertical routing"}',2,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
	 		(165,'{technology}','{Technology}',None,'Type of technology','{cfet,gaa,finfet}','{CFET,GAA,FinFET}','{"Select cfet technology","Select gaa technology","Select finFET technology"}',2,2,True,False,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(166,'{half_dr}','{"Half DR Compliance"}',None,'Switch for Half DR compliance','{True,False}','{True,False}','{"Generates half DR compliant layouts","Generates half DR non-compliant layouts"}',2,2,True,False,False,False,False,False,1,None,None,None,None,None,None,None,None),
			(167,'{number_of_routing_tracks}','{"Number of routing tracks"}',None,'Number of routing tracks per cell',None,None,None,2,2,True,True,True,False,False,False,1,None,None,None,None,None,None,None,None),
			(168,'{height_req}','{"Height Requirement"}',None,'Controls height of mult-height cell',None,None,None,2,3,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(169,'{placer}','{Placer}',None,'Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon','{base0,base1}','{base0,base1}','{"Uses base0 placement algorithm","Uses base1 placement algorithm"}',2,3,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(170,'{inner_space_width}','{"Poly to Diffcon spacing"}','nm','Horizontal Distance between ppoly/npoly and pdiffcon/ndiffcon',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(171,'{"np_spacing"}', '{"N/P Diffusion spacing"}', 'nm', 'In GAA and FinFET only, the distance between pdiff and ndiff', None, None, None, 2,5, True, True, True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(172,'{"pg_signal_spacing"}', '{"PG rails to Signal spacing"}', 'nm', 'For Frontside Power, distance between power/ground and signals for Metal0', None, None, None, 2,5, True, True, True,False,False,True,0.5,None,None,None,None,None,None,None,None),	
	 		(173,'{l_nanosheet,diff_interconnect}','{"Diffusion to Diff interconnect spacing"}','nm','In CFET only, Minimum spacing between Diffusion and Diff interconnect',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(174,'{"via_extension"}','{"Via extension"}','nm','Used to change the all vias(except dvb, Diff Interconnect) size in both X and Y direction simultaneously',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(175,'{"gate_extension"}','{"Gate extension"}','nm','Extension of poly layer from diffusion(nanosheet)',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(176,'{"interconnect_extension"}','{"Diffcon extension"}','nm','Extension of Diffcon layer from diffusion(nanosheet)',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(177,'{"vertical_gate_spacing"}','{"Gate Cut spacing"}','nm','In GAA & FinFET only, end to end spacing between ppoly and npoly',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(178,'{"vertical_interconnect_spacing"}','{"Diffcon ETE spacing"}','nm','For GAA and FinFET only, end to end spacing between pdiffcon and ndiffcon',None,None,None,2,5,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(179,'{nanosheet_width}','{"Diffusion width"}','nm','Width of Diffusion/Nanosheet',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(180,'{power_rail_width}','{"Power rail width"}','nm','Width of back metal power rail',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(181,'{m0_pitch}','{"Metal0 routing pitch"}','nm','Routing pitch for horizontal metal( Metal0)',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(182,'{"vertical_metal_pitch"}','{"Metal1 routing pitch"}','nm','For Two metal solution, routing pitch for vertical metal (Metal1,None,None,None,None,None,None,None,None)',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(183,'{pdiffcon}','{"P-diffcon width"}','nm','Changes cell width',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(184,'{npoly}','{"N-poly width"}','nm','Transistor gate length of nFET is changed',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(185,'{ppoly}','{"P-poly width"}','nm','Transistor gate length of pFET is changed',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(186,'{metal0}','{"M0 width"}','nm','Width of Metal0 Wire (Y direction)',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(187,'{ndiffcon}','{"N-diffcon width"}','nm','Changes cell width',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(188,'{metal0_track_guide}','{"M0 track guide"}','nm','Width of Metal0 tracks (Y direction) for visualization for foundry users',None,None,None,2,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(189,'{metal1}','{"M1 width"}','nm','Width of Metal1 Wire (X direction)',None,None,None,2,4,True,True,True,False,False,True,0.5,None,None,None,None,None,None,None,None),
	 		(190,'{metal1_track_guide}','{"M1 track guide"}','nm','Width of Metal1 tracks (X direction) for visualization for foundry users',None,None,None,2,4,True,True,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(191,'{poly}','{"poly"}','nm','Length of poly (X direction)',None,None,None,2,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
			(192,'{diffcon}','{"diffcon"}','nm','Length of diffcon (X direction)',None,None,None,2,4,False,False,False,False,False,True,0.5,None,None,None,None,None,None,None,None),
    		]