# Generated by Django 5.1.3 on 2025-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_activetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log_level',
            field=models.IntegerField(default=0),
        ),
    ]
