# Generated by Django 5.1.3 on 2025-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_user_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log_level',
            field=models.IntegerField(default=99),
        ),
    ]
