# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\x03lvs\x1a\x1cgoogle/protobuf/struct.proto\"\xbf\x01\n\x0e\x42ulkLVSRequest\x12\x11\n\tcell_name\x18\x01 \x01(\t\x12\x14\n\x0cnetlist_path\x18\x02 \x01(\t\x12\x16\n\x0escaling_factor\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06length\x18\x05 \x01(\x05\x12\x12\n\ntechnology\x18\x06 \x01(\t\x12\x13\n\x0blayer_stack\x18\x07 \x01(\t\x12\x10\n\x08gdsjsons\x18\x08 \x01(\t\x12\x12\n\nheight_req\x18\t \x01(\x05\"r\n\x0f\x42ulkLVSResponse\x12\x30\n\x06result\x18\x01 \x03(\x0b\x32 .lvs.BulkLVSResponse.ResultEntry\x1a-\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x10LayoutGenRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\t\"2\n\x0fSiVistaResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xc5\x01\n\x0cRemapRequest\x12\x12\n\ntechnology\x18\x01 \x01(\t\x12\x14\n\x0cinput_folder\x18\x02 \x01(\t\x12\x15\n\routput_folder\x18\x03 \x01(\t\x12-\n\x06params\x18\x04 \x03(\x0b\x32\x1d.lvs.RemapRequest.ParamsEntry\x1a\x45\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"\x07\n\x05\x45mpty2\xde\x01\n\nLVSService\x12\x34\n\x07\x42ulkLVS\x12\x13.lvs.BulkLVSRequest\x1a\x14.lvs.BulkLVSResponse\x12\x38\n\tLayoutGen\x12\x15.lvs.LayoutGenRequest\x1a\x14.lvs.SiVistaResponse\x12\x33\n\x08GTSRemap\x12\x11.lvs.RemapRequest\x1a\x14.lvs.SiVistaResponse\x12+\n\x07Version\x12\n.lvs.Empty\x1a\x14.lvs.SiVistaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BULKLVSRESPONSE_RESULTENTRY']._options = None
  _globals['_BULKLVSRESPONSE_RESULTENTRY']._serialized_options = b'8\001'
  _globals['_REMAPREQUEST_PARAMSENTRY']._options = None
  _globals['_REMAPREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_BULKLVSREQUEST']._serialized_start=58
  _globals['_BULKLVSREQUEST']._serialized_end=249
  _globals['_BULKLVSRESPONSE']._serialized_start=251
  _globals['_BULKLVSRESPONSE']._serialized_end=365
  _globals['_BULKLVSRESPONSE_RESULTENTRY']._serialized_start=320
  _globals['_BULKLVSRESPONSE_RESULTENTRY']._serialized_end=365
  _globals['_LAYOUTGENREQUEST']._serialized_start=367
  _globals['_LAYOUTGENREQUEST']._serialized_end=399
  _globals['_SIVISTARESPONSE']._serialized_start=401
  _globals['_SIVISTARESPONSE']._serialized_end=451
  _globals['_REMAPREQUEST']._serialized_start=454
  _globals['_REMAPREQUEST']._serialized_end=651
  _globals['_REMAPREQUEST_PARAMSENTRY']._serialized_start=582
  _globals['_REMAPREQUEST_PARAMSENTRY']._serialized_end=651
  _globals['_EMPTY']._serialized_start=653
  _globals['_EMPTY']._serialized_end=660
  _globals['_LVSSERVICE']._serialized_start=663
  _globals['_LVSSERVICE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
