# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_service import grpc_service_pb2 as grpc__service__pb2


class LVSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BulkLVS = channel.unary_unary(
                '/lvs.LVSService/BulkLVS',
                request_serializer=grpc__service__pb2.BulkLVSRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.BulkLVSResponse.FromString,
                )
        self.LayoutGen = channel.unary_unary(
                '/lvs.LVSService/LayoutGen',
                request_serializer=grpc__service__pb2.LayoutGenRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.SiVistaResponse.FromString,
                )
        self.GTSRemap = channel.unary_unary(
                '/lvs.LVSService/GTSRemap',
                request_serializer=grpc__service__pb2.RemapRequest.SerializeToString,
                response_deserializer=grpc__service__pb2.SiVistaResponse.FromString,
                )
        self.Version = channel.unary_unary(
                '/lvs.LVSService/Version',
                request_serializer=grpc__service__pb2.Empty.SerializeToString,
                response_deserializer=grpc__service__pb2.SiVistaResponse.FromString,
                )


class LVSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BulkLVS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LayoutGen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GTSRemap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LVSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BulkLVS': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkLVS,
                    request_deserializer=grpc__service__pb2.BulkLVSRequest.FromString,
                    response_serializer=grpc__service__pb2.BulkLVSResponse.SerializeToString,
            ),
            'LayoutGen': grpc.unary_unary_rpc_method_handler(
                    servicer.LayoutGen,
                    request_deserializer=grpc__service__pb2.LayoutGenRequest.FromString,
                    response_serializer=grpc__service__pb2.SiVistaResponse.SerializeToString,
            ),
            'GTSRemap': grpc.unary_unary_rpc_method_handler(
                    servicer.GTSRemap,
                    request_deserializer=grpc__service__pb2.RemapRequest.FromString,
                    response_serializer=grpc__service__pb2.SiVistaResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=grpc__service__pb2.Empty.FromString,
                    response_serializer=grpc__service__pb2.SiVistaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lvs.LVSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LVSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BulkLVS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lvs.LVSService/BulkLVS',
            grpc__service__pb2.BulkLVSRequest.SerializeToString,
            grpc__service__pb2.BulkLVSResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LayoutGen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lvs.LVSService/LayoutGen',
            grpc__service__pb2.LayoutGenRequest.SerializeToString,
            grpc__service__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GTSRemap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lvs.LVSService/GTSRemap',
            grpc__service__pb2.RemapRequest.SerializeToString,
            grpc__service__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lvs.LVSService/Version',
            grpc__service__pb2.Empty.SerializeToString,
            grpc__service__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
