# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_service import protobuf_stream_pb2 as protobuf__stream__pb2
class SiVistaLayoutStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LayoutGen = channel.unary_stream(
                '/layout.SiVistaLayout/LayoutGen',
                request_serializer=protobuf__stream__pb2.LayoutGenRequest.SerializeToString,
                response_deserializer=protobuf__stream__pb2.SiVistaResponse.FromString,
                )
        self.Hyperexpressivity = channel.unary_stream(
                '/layout.SiVistaLayout/Hyperexpressivity',
                request_serializer=protobuf__stream__pb2.HyperexpressivityRequest.SerializeToString,
                response_deserializer=protobuf__stream__pb2.SiVistaResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/layout.SiVistaLayout/GetVersion',
                request_serializer=protobuf__stream__pb2.Empty.SerializeToString,
                response_deserializer=protobuf__stream__pb2.SiVistaResponse.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/layout.SiVistaLayout/GetFile',
                request_serializer=protobuf__stream__pb2.FilePathRequest.SerializeToString,
                response_deserializer=protobuf__stream__pb2.SiVistaResponse.FromString,
                )


class SiVistaLayoutServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LayoutGen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hyperexpressivity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiVistaLayoutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LayoutGen': grpc.unary_stream_rpc_method_handler(
                    servicer.LayoutGen,
                    request_deserializer=protobuf__stream__pb2.LayoutGenRequest.FromString,
                    response_serializer=protobuf__stream__pb2.SiVistaResponse.SerializeToString,
            ),
            'Hyperexpressivity': grpc.unary_stream_rpc_method_handler(
                    servicer.Hyperexpressivity,
                    request_deserializer=protobuf__stream__pb2.HyperexpressivityRequest.FromString,
                    response_serializer=protobuf__stream__pb2.SiVistaResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=protobuf__stream__pb2.Empty.FromString,
                    response_serializer=protobuf__stream__pb2.SiVistaResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=protobuf__stream__pb2.FilePathRequest.FromString,
                    response_serializer=protobuf__stream__pb2.SiVistaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'layout.SiVistaLayout', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SiVistaLayout(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LayoutGen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/layout.SiVistaLayout/LayoutGen',
            protobuf__stream__pb2.LayoutGenRequest.SerializeToString,
            protobuf__stream__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Hyperexpressivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/layout.SiVistaLayout/Hyperexpressivity',
            protobuf__stream__pb2.HyperexpressivityRequest.SerializeToString,
            protobuf__stream__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/layout.SiVistaLayout/GetVersion',
            protobuf__stream__pb2.Empty.SerializeToString,
            protobuf__stream__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/layout.SiVistaLayout/GetFile',
            protobuf__stream__pb2.FilePathRequest.SerializeToString,
            protobuf__stream__pb2.SiVistaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
