name: Build and Deploy to Kubernetes

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set Env Variables
      id: set_repo_variables
      run: |
           cat env/dev/.env >>${GITHUB_ENV}
           
    - name: Print all env vars
      run: env

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.SIVISTA_DEV_SA_KEY }}

          
    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
           docker build -t ${gcrname}/${gcrrepositoryname}:${{ github.sha }} .

    - name: Push image to GCR
      run: docker push ${gcrname}/${gcrrepositoryname}:${{ github.sha }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_REGION }}

    - name: Replace placeholders in manifest in-place
      run: |
        export GITHUB_SHA=${{ github.sha }}
        envsubst < k8s/deployment.yaml > k8s/deployment.yaml.tmp
        mv k8s/deployment.yaml.tmp k8s/deployment.yaml

    - name: Deploy to ${{ inputs.environment }}
      run: |
        kubectl apply -f k8s/deployment.yaml
