name: SiVista_Dev_k8s_deploy

on:
  push:
    branches:
      - main

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from build.sh
        id: extract_version
        run: |
          version=$(grep -oP 'VERSION="\K[^"]+' build.sh)
          echo "Version is: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: extract-version
   
    env:
      CI: true
      REACT_APP_API_URL: http://13.126.133.62:6601

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build . \
          --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} \
          --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
          -t ghcr.io/${{ github.repository }}/sivista_frontend_sprint4:${{ needs.extract-version.outputs.version }}

  push:
    runs-on: ubuntu-latest
    needs: [build, extract-version]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/sivista_frontend_sprint4:${{ needs.extract-version.outputs.version }}