name: SiVista_Dev_k8s_deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version from build.sh
        id: extract_version
        run: |
          version=$(grep -oP 'VERSION="\K[^"]+' build.sh)
          echo "Version is: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Log Push Details
        run: |
          echo "Push event to branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set dynamic environment variables
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_NAME}/sivista_frontend_sprint4"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            --label org.opencontainers.image.source=https://github.com/$REPO_NAME \
            -t $IMAGE_NAME:${{ steps.extract_version.outputs.version }} .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ steps.extract_version.outputs.version }}