name: SiVista_Dev_k8s_deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    env:
      CI: true
 
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Extract Version from build.sh
        id: extract_version
        run: |
          version=$(grep -oP 'VERSION="\K[^"]+' build.sh)
          echo "Version is: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Log Push Details
        run: |
          echo "Push event to branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}" 
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Create .env file dynamically
        run: |
          echo "REACT_APP_API_URL=http://13.126.133.62:3001" >> .env
      - name: Build and Push Docker Image to GHCR
        run: |
          docker build . --label org.opencontainers.image.source=https://github.com/devang-k/k8s \
          -t ghcr.io/${{ github.repository }}/sivista_frontend_sprint4:${{ steps.extract_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}/sivista_frontend_sprint4:${{ steps.extract_version.outputs.version }}