name: SiVista_Dev_k8s_deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CI: true
      REACT_APP_API_URL: "http://13.126.133.62:6601"
      REACT_APP_WEBSOCKET_API_URL: "ws://13.126.133.62:6601/ws/job"
      REACT_APP_DEBUG: "true"
      GENERATE_SOURCEMAP: "false"
      REACT_APP_ENABLE_POC_BUTTON: "true"
      REACT_APP_CURRENT_APP_VERSION: "2"
      PORT: "3000"
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/sivista_frontend_sprint4"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version from build.sh
        id: extract_version
        run: |
          version=$(grep -oP 'VERSION="\K[^"]+' build.sh)
          echo "Version is: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Log Push Details
        run: |
          echo "Push event to branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        run: |
          docker build . \
          --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} \
          --build-arg REACT_APP_WEBSOCKET_API_URL=${{ env.REACT_APP_WEBSOCKET_API_URL }} \
          --build-arg REACT_APP_DEBUG=${{ env.REACT_APP_DEBUG }} \
          --build-arg GENERATE_SOURCEMAP=${{ env.GENERATE_SOURCEMAP }} \
          --build-arg REACT_APP_ENABLE_POC_BUTTON=${{ env.REACT_APP_ENABLE_POC_BUTTON }} \
          --build-arg REACT_APP_CURRENT_APP_VERSION=${{ env.REACT_APP_CURRENT_APP_VERSION }} \
          --build-arg PORT=${{ env.PORT }} \
          --label org.opencontainers.image.source=https://github.com/${{ github.repository }} \
          -t ${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}