name: SiVista_Dev_k8s_deploy

on:
  push:
    branches:
      - main-ml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PORT: 50051
      ML_ENV: .env.dev
      AWS_ACCESS_KEY_ID_DEV: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY_DEV: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_STORAGE_BUCKET_NAME_DEV: sivista-dev-k8s-storage
      AWS_S3_REGION_NAME_DEV: ap-south-1
      SHARED_MEMORY: /app/shared_memory/
      mount_source: shared_memory_volume_sivista_integration
      mount_target: /app/shared_memory
      THIRD_PARTY_GRPC: 13.126.133.62:30003
      STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
      IMAGE_NAME: siclarity/sivista_ml
      CONTAINER_NAME: sivistaML
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version from version.conf
        id: extract_version
        run: |
          version=$(grep 'VERSION=' version.conf | cut -d '"' -f 2)
          echo "Version is: $version"
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Log Push Details
        run: |
          echo "Push event to branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PATL }}

      - name: Set dynamic environment variables
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_NAME}/sivista_ml_sprint4"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build --no-cache --progress=plain \
            --build-arg ML_ENV=.env.dev \
            --build-arg AWS_ACCESS_KEY_ID_DEV=${{ secrets.AWS_ACCESS_KEY_ID_DEV }} \
            --build-arg AWS_SECRET_ACCESS_KEY_DEV=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }} \
            --build-arg AWS_STORAGE_BUCKET_NAME_DEV=sivista-dev-k8s-storage \
            --build-arg AWS_S3_REGION_NAME_DEV=ap-south-1 \
            --build-arg SHARED_MEMORY=/app/shared_memory/ \
            --build-arg mount_source=shared_memory_volume_sivista_k8s \
            --build-arg mount_target=/app/shared_memory \
            --build-arg THIRD_PARTY_GRPC=13.126.133.62:30003 \
            --build-arg STORAGE_TYPE=${{ secrets.STORAGE_TYPE }} \
            --build-arg IMAGE_NAME=siclarity/sivista_ml \
            --build-arg CONTAINER_NAME=sivistaML \
            --label org.opencontainers.image.source=https://github.com/$REPO_NAME \
            -t $IMAGE_NAME:${{ steps.extract_version.outputs.version }} .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ steps.extract_version.outputs.version }}
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
